// <auto-generated />
using System;
using Core3Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core3Database.Migrations
{
    [DbContext(typeof(mydbContext))]
    partial class mydbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1");

            modelBuilder.Entity("Core3Database.tbl_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LName");

                    b.Property<string>("NameX");

                    b.Property<byte[]>("Profile");

                    b.HasKey("Id");

                    b.ToTable("tbl_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
